In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Vamos a usar el documento 'vino.csv' que hemos guardado de nuestra carpeta del proyecto (C:\Users\34649\Documents\Machine Learning Data Science)
vinos = pd.read_csv('vino.csv')
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [3]:
#Vamos a ver losn distintos valores que posee la columna 'Wine Types'
vinos['Wine Type'].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [4]:
#Podemos ver el nº de vinos de cada tipo:
vinos['Wine Type'].value_counts()

Wine Type
Two      71
One      59
Three    48
Name: count, dtype: int64

In [5]:
# Separamos las variables de la vble que queremos predecir(Wine Type)
x= vinos.drop('Wine Type', axis=1)
y= vinos['Wine Type']

In [6]:
# Dividimos el dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [8]:
# Creamos y entrenamos el modelo
from sklearn.tree import DecisionTreeClassifier
arbol = DecisionTreeClassifier()
arbol.fit(x_train, y_train)

DecisionTreeClassifier()

In [9]:
# Creamos nuestras propias predicciones
predicciones = arbol.predict(x_test)

In [10]:
predicciones

array(['One', 'Two', 'One', 'One', 'Two', 'One', 'Two', 'Two', 'Three',
       'One', 'Three', 'One', 'One', 'Three', 'One', 'Two', 'One',
       'Three', 'Two', 'One', 'Three', 'One', 'Three', 'Two', 'One',
       'Two', 'Two', 'Two', 'One', 'Two', 'Two', 'Two', 'Two', 'Two',
       'One', 'One', 'Two', 'Two', 'One', 'Three', 'Three', 'One',
       'Three', 'Two', 'One', 'Two', 'Two', 'One', 'One', 'One', 'Three',
       'One', 'Two', 'One'], dtype=object)

In [11]:
#Estos son los valores reales, lo q vamos a comprarar con las predicciones
y_test

50       One
126      Two
40       One
42       One
92       Two
34       One
84       Two
82       Two
167    Three
15       One
142    Three
46       One
20       One
153    Three
45       One
43       One
48       One
145    Three
79       Two
28       One
134    Three
44       One
144    Three
128      Two
51       One
69       Two
76       Two
101      Two
14       One
111      Two
95       Two
78       Two
71       Two
150    Three
21       One
52       One
136    Three
63       Two
13       One
169    Three
147    Three
23       One
135    Three
83       Two
8        One
105      Two
87       Two
0        One
1        One
39       One
155    Three
29       One
110      Two
10       One
Name: Wine Type, dtype: object

In [12]:
# Evaluamos el modelo:
from sklearn.metrics import classification_report, confusion_matrix

In [13]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       1.00      0.96      0.98        24
       Three       1.00      0.83      0.91        12
         Two       0.86      1.00      0.92        18

    accuracy                           0.94        54
   macro avg       0.95      0.93      0.94        54
weighted avg       0.95      0.94      0.94        54



In [14]:
print(confusion_matrix(y_test, predicciones))

[[23  0  1]
 [ 0 10  2]
 [ 0  0 18]]
