RANDOM FOREST (ÁRBOLES ALEATORIOS)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Volvemos a usar el dataset de vinos
vinos = pd.read_csv('vino.csv')

In [3]:
#Mostramos las primeras filas de nuestra tabla
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [4]:
# Nuestra columna objetivo será 'Wine Type'
x= vinos.drop('Wine Type', axis=1)
y=vinos['Wine Type']

In [5]:
# Dividimos el dataset:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [22]:
# Creamos y entrenamos el modelo. Tenemos que pasarle el nº de estimadores (árboles):
from sklearn.ensemble import RandomForestClassifier

In [23]:
rf = RandomForestClassifier(n_estimators=80)
rf.fit(x_train, y_train)

RandomForestClassifier(n_estimators=80)

In [24]:
# Hacemos las preedicciones
predicciones = rf.predict(x_test)

In [25]:
predicciones

array(['Two', 'One', 'One', 'Two', 'One', 'One', 'Three', 'Two', 'Two',
       'Three', 'Three', 'Two', 'One', 'One', 'One', 'Two', 'Two', 'One',
       'Three', 'Two', 'Two', 'Two', 'Two', 'Three', 'Two', 'Three',
       'Three', 'Three', 'Three', 'Two', 'Two', 'Two', 'One', 'One',
       'One', 'Three', 'One', 'One', 'Three', 'Three', 'One', 'Three',
       'Two', 'Two', 'Three', 'Two', 'One', 'One', 'Two', 'One', 'Three',
       'One', 'Three', 'Three'], dtype=object)

In [26]:
y_test

79       Two
22       One
73       Two
66       Two
17       One
31       One
171    Three
59       Two
125      Two
130    Three
165    Three
92       Two
0        One
46       One
18       One
98       Two
82       Two
42       One
174    Three
122      Two
74       Two
64       Two
85       Two
136    Three
109      Two
175    Three
145    Three
163    Three
167    Three
89       Two
96       Two
104      Two
35       One
23       One
45       One
148    Three
44       One
3        One
141    Three
147    Three
27       One
140    Three
101      Two
84       Two
70       Two
65       Two
49       One
5        One
71       Two
52       One
149    Three
47       One
157    Three
150    Three
Name: Wine Type, dtype: object

In [28]:
# Evaluamos el modelo
from sklearn.metrics import classification_report, confusion_matrix

In [29]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       0.94      1.00      0.97        17
       Three       0.94      1.00      0.97        16
         Two       1.00      0.90      0.95        21

    accuracy                           0.96        54
   macro avg       0.96      0.97      0.96        54
weighted avg       0.97      0.96      0.96        54



In [30]:
print(confusion_matrix(y_test, predicciones))

[[17  0  0]
 [ 0 16  0]
 [ 1  1 19]]
