Numpy con listas

In [2]:
import numpy as np

In [4]:
lista = [1,2,3,4]
#Ahora creamos un vector
array= np.array(lista)

In [5]:
array

array([1, 2, 3, 4])

In [6]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]
array2 = np.array(lista2)

In [7]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Numpy arrays - arange, zeros, ones, linspace, eye

In [8]:
array = np.arange(5)

In [9]:
array

array([0, 1, 2, 3, 4])

In [12]:
array2 = np.arange(2,10)

In [13]:
array2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
array3 = np.arange(2,10,2)

In [17]:
array3

array([2, 4, 6, 8])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros ((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones ((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
np.linspace(5,8,50)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [23]:
np.linspace(3,9,20)

array([3.        , 3.31578947, 3.63157895, 3.94736842, 4.26315789,
       4.57894737, 4.89473684, 5.21052632, 5.52631579, 5.84210526,
       6.15789474, 6.47368421, 6.78947368, 7.10526316, 7.42105263,
       7.73684211, 8.05263158, 8.36842105, 8.68421053, 9.        ])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(5)

array([0.48224781, 0.20121531, 0.06915061, 0.50753371, 0.26160408])

In [27]:
np.random.rand(3,5)

array([[0.28899829, 0.3337264 , 0.80613842, 0.22943224, 0.04058425],
       [0.18673739, 0.22495395, 0.67845864, 0.28527356, 0.64860071],
       [0.29659095, 0.41701001, 0.89625168, 0.35983308, 0.96969184]])

In [28]:
np.random.randn(5)

array([ 2.40467054,  0.57479235, -0.20304015,  0.48815487, -0.1680166 ])

In [29]:
np.random.rand(3,5)

array([[0.04545525, 0.35760497, 0.12523643, 0.67835593, 0.29933434],
       [0.5952035 , 0.60880594, 0.63844078, 0.49567925, 0.00399004],
       [0.60976056, 0.07641121, 0.5296656 , 0.22446588, 0.97810713]])

Números aleatorios enteros

In [3]:
# Creammos un nº aleatorio cuyo valor está entre 1 y 19
np.random.randint(1,20)

11

In [4]:
#Si ahora, en vez de 1, queremos crear un  array de, x ejemplo, 5 nº
np.random.randint(1,20,5)

array([ 9,  3, 11, 17, 15])