In [1]:
import numpy as np

In [2]:
array = np.random.randint(1,100,25)

In [3]:
array

array([31,  2, 69, 81, 33, 64, 55, 87, 13, 13, 68, 20, 15, 54, 95, 86,  4,
       88, 63, 52, 46, 76, 25, 81, 85])

In [4]:
# Si queremos transformar este array en una matriz de 2 dimensiones:
matriz = array.reshape(5,5)

In [5]:
matriz

array([[31,  2, 69, 81, 33],
       [64, 55, 87, 13, 13],
       [68, 20, 15, 54, 95],
       [86,  4, 88, 63, 52],
       [46, 76, 25, 81, 85]])

Valor máximo y mínimo de un array

In [6]:
array2 = np.random.randint(1,100,50)

In [7]:
array2

array([54, 27, 87, 26, 93, 80, 95, 47, 40, 57, 48, 42, 24, 11, 97, 95, 34,
        5, 29, 83, 33, 38, 63, 38, 81, 73, 52, 12, 88, 60, 64, 31, 68, 21,
       92, 54, 52, 65, 97, 79, 75, 17, 28, 60, 29,  8, 69,  9, 13, 59])

In [10]:
matriz2 = array2.reshape(5,10)

In [16]:
matriz2

array([[54, 27, 87, 26, 93, 80, 95, 47, 40, 57],
       [48, 42, 24, 11, 97, 95, 34,  5, 29, 83],
       [33, 38, 63, 38, 81, 73, 52, 12, 88, 60],
       [64, 31, 68, 21, 92, 54, 52, 65, 97, 79],
       [75, 17, 28, 60, 29,  8, 69,  9, 13, 59]])

In [12]:
valor_maximo = array2.max()

In [13]:
valor_maximo

97

In [14]:
#Si queremos saber en que poición está el valor máximo:
posicion_valor_max = array2.argmax()

In [15]:
posicion_valor_max

14

In [17]:
valor_minimo = array2.min()

In [18]:
valor_minimo

5

In [21]:
posicion_valor_min = array2.argmin()

In [22]:
posicion_valor_min

17

Indexacion en arrays

In [23]:
array3 = np.arange(0,10)
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#Primera posición del array
array3[0]

0

In [26]:
#Última posición del array
array3[-1]

9

In [27]:
#De la posición 2 a la 5
array3[2:5]

array([2, 3, 4])

In [29]:
#De la posición inicial a la 5
array3[:5]

array([0, 1, 2, 3, 4])

In [30]:
#De la posición 5 al final
array3[5:]

array([5, 6, 7, 8, 9])

In [31]:
#Todo el array
array3[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Copia del array
array4 = array3.copy()
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
array4[0] = 100
array4

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [34]:
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Indexación en arrays de 2 o + dimensiones

In [36]:
#Creamos una matriz de 3 dimensiones
array5 = np.array([[1,2,3], [4,5,6], [7,8,9]])
array5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
#Con esto obtenemos la primera fila entera
array5[0]

array([1, 2, 3])

In [41]:
array6 = array5[:2]
array6

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
array5[0][0]

1

In [45]:
array5[0,0]

1

In [46]:
array5[1,1]

5

In [47]:
#Para seleccionar 1 columna:
array5[:, 0]

array([1, 4, 7])

In [50]:
#Si queremos las 2 primeras columnas:
array5[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

Seleccionar elementos de un array según condición

In [51]:
#Creamos un array
array7= np.arange(0,10)
array7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
condicion = array7>5

In [53]:
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [54]:
array7[condicion]

array([6, 7, 8, 9])

In [56]:
array7[array7<=2]

array([0, 1, 2])

In [58]:
array7[array7%2==0]

array([0, 2, 4, 6, 8])

Operaciones sobre los arrays

In [59]:
#Sumas:
array7+array7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
array7*100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [61]:
array7+40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [65]:
array7-array7

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
(array7*2)-array7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.sqrt(array7)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [67]:
#Ejercicio1
#Crea una lista de elementos secuenciales con el valor mínimo de 10 y el máximo de 39.
#Convierte esa lista en una matriz de 3x10
#Accede al elemento de la esqina superior derecha de la matriz
lista = np.arange(10,40)
lista

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [73]:
lista = lista.reshape(3,10)

In [74]:
lista

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [75]:
lista[0,-1]

19

In [76]:
# Ejercicio 2
# Crea un array de 1 dimensión con 9 valores enteros aleatorios entre 0 y 100
# Convierte este array en una matriz de 3x3
# Muestra por pantalla el valor del elemento de la matriz de la esquina inferior derecha
array = np.random.randint(0,100,9)
array

array([91, 94, 14, 83, 95, 44, 92, 14, 97])

In [77]:
matriz = array.reshape(3,3)
matriz

array([[91, 94, 14],
       [83, 95, 44],
       [92, 14, 97]])

In [78]:
matriz[-1,-1]

97

In [80]:
array10 = np.arange(0,10,2)

In [82]:
array10

array([0, 2, 4, 6, 8])