Crearlista asignaturas ='Matematicas', 'Fisica', 'Historia'; Crear lista notas=9,9,8; Crear serie de la lista de notas como valores 
y la lista de asignaturas como índices; crear variable nota_fisica con la nota de fisica; Imprimir "La nota de fisica es ..."

In [1]:
import numpy as np
import pandas as pd

In [2]:
asignaturas = ['Matematicas', 'Fisica', 'Historia']
notas = [9,9,8]
pd.Series(data= notas, index = asignaturas)

Matematicas    9
Fisica         9
Historia       8
dtype: int64

In [3]:
serie = pd.Series(data= notas, index = asignaturas)
serie

Matematicas    9
Fisica         9
Historia       8
dtype: int64

In [7]:
nota_fisica =serie['Fisica']
nota_fisica

9

In [10]:
print ("La nota de fisica es: {}".format(nota_fisica))

La nota de fisica es: 9


Crear dataframe con las ventas de nuestras 3 oficinas para los meses de enero, febrero y marzo. Pasos a seguir:
1. Crear variable ventas_enero que contenga una lista de 3 nº enteros aleatorios entre 100 y 500
2. Crear variable ventas_febrero que contenga una lista de 3 nº enteros aleatorios entre 100 y 500
3. Crear variable ventas_marzo que contenga una lista de 3 nº enteros aleatorios entre 100 y 500
4. Crear variable filas que contenga : "ventas_enero", "ventas_febrero", "ventas_marzo"
5. Crear variable columnas que contenga : "oficina1", "oficina2", "oficina3"
6. Crear variable ventas que contenga una lista con las ventas de enero, febrero y marzo
7. Crear dataframe que contenga ventas, filas y columnas
8. Mediante print mostrar: "Las ventas de enero para la oficina 1 son de: "

In [14]:
ventas_enero = np.random.randint(100,500,3)

In [15]:
ventas_enero

array([346, 219, 427])

In [16]:
ventas_febrero = np.random.randint(100,500,3)
ventas_febrero

array([202, 485, 366])

In [18]:
ventas_marzo = np.random.randint(100,500,3)
ventas_marzo

array([492, 185, 186])

In [19]:
filas = "ventas_enero", "ventas_febrero", "ventas_marzo"

In [20]:
columnas = "oficina1", "oficina2", "oficina3"

In [22]:
ventas = [ventas_enero, ventas_febrero, ventas_marzo]
ventas

[array([346, 219, 427]), array([202, 485, 366]), array([492, 185, 186])]

In [23]:
dataframe= pd.DataFrame(ventas, filas, columnas)
dataframe

oficina1  oficina2  oficina3
ventas_enero         346       219       427
ventas_febrero       202       485       366
ventas_marzo         492       185       186

In [28]:
print ("Las ventas de enero para la oficina 1 son: {}".format(dataframe['oficina1']['ventas_enero']))

Las ventas de enero para la oficina 1 son: 346


In [31]:
import pandas as pd

def rellenar_con_media(dataframe, columna):
    media = dataframe[columna].mean()
    resultado = dataframe.fillna(media)
    return resultado
    
data = {
    'nombre': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'edad': [20, None, 18, 25, None],
    'calificaciones': [90, 88, None, None, 95]
}
 
df = pd.DataFrame(data)
columna = 'calificaciones'
 
resultado = rellenar_con_media(df, columna)
print(resultado)

    nombre  edad  calificaciones
0    Alice  20.0            90.0
1      Bob  91.0            88.0
2  Charlie  18.0            91.0
3    David  25.0            91.0
4      Eve  91.0            95.0
